<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="QueryService.FoldersListBox():System.Void")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", Scope:="member", Target:="Microsoft.Samples.SqlServer.CatalogManager..ctor(System.String)", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Microsoft.Samples.SqlServer")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.SetSubscriptionPropertiesAsync(System.String,ExtensionSettings,System.String,System.String,System.String,ParameterValue[],System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.SetSubscriptionPropertiesAsync(System.String,ExtensionSettings,System.String,System.String,System.String,ParameterValue[]):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.SetSchedulePropertiesAsync(System.String,System.String,ScheduleDefinition,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.SetSchedulePropertiesAsync(System.String,System.String,ScheduleDefinition):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.SetModelItemPoliciesAsync(System.String,System.String,Policy[],System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.SetModelItemPoliciesAsync(System.String,System.String,Policy[]):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.SetModelDrillthroughReportsAsync(System.String,System.String,ModelDrillthroughReport[],System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.SetModelDrillthroughReportsAsync(System.String,System.String,ModelDrillthroughReport[]):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.SetDataDrivenSubscriptionPropertiesAsync(System.String,ExtensionSettings,DataRetrievalPlan,System.String,System.String,System.String,ParameterValueOrFieldReference[],System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.SetDataDrivenSubscriptionPropertiesAsync(System.String,ExtensionSettings,DataRetrievalPlan,System.String,System.String,System.String,ParameterValueOrFieldReference[]):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.ResumeScheduleAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.PauseScheduleAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.ListScheduledReportsAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.ListModelItemChildrenAsync(System.String,System.String,System.Boolean):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.ListModelItemChildrenAsync(System.String,System.String,System.Boolean,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.ListModelDrillthroughReportsAsync(System.String,System.String,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.ListModelDrillthroughReportsAsync(System.String,System.String):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.InheritModelItemParentSecurityAsync(System.String,System.String,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.InheritModelItemParentSecurityAsync(System.String,System.String):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.GetSubscriptionPropertiesAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.GetSchedulePropertiesAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.GetReportParametersAsync(System.String,System.String,System.Boolean,ParameterValue[],DataSourceCredentials[],System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.GetReportParametersAsync(System.String,System.String,System.Boolean,ParameterValue[],DataSourceCredentials[]):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.GetModelItemPoliciesAsync(System.String,System.String,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.GetModelItemPoliciesAsync(System.String,System.String):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.GetModelItemPermissionsAsync(System.String,System.String,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.GetModelItemPermissionsAsync(System.String,System.String):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.GetDataDrivenSubscriptionPropertiesAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope:="member", Target:="ReportingService2005.FireEventAsync(System.String,System.String,System.Object):System.Void")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope:="member", Target:="ReportingService2005.FireEventAsync(System.String,System.String):System.Void")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.DeleteSubscriptionAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.DeleteScheduleAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.DeleteReportHistorySnapshotAsync(System.String,System.String,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.DeleteReportHistorySnapshotAsync(System.String,System.String):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="ReportingService2005.CancelJobAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope:="member", Target:="ReportingService2005..ctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", Scope:="type", Target:="Property")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1050:DeclareTypesInNamespaces", Scope:="type", Target:="Property")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", Scope:="type", Target:="Event")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1050:DeclareTypesInNamespaces", Scope:="type", Target:="Event")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", Scope:="member", Target:="CatalogManager..ctor(System.String)", MessageId:="0#")> 
