<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.Explorer.EditItem(System.String,System.String):System.Void")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.SetSubscriptionPropertiesAsync(System.String,Microsoft.Samples.ReportingServices.RSExplorer.ExtensionSettings,System.String,System.String,System.String,Microsoft.Samples.ReportingServices.RSExplorer.ParameterValue[],System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.SetSubscriptionPropertiesAsync(System.String,Microsoft.Samples.ReportingServices.RSExplorer.ExtensionSettings,System.String,System.String,System.String,Microsoft.Samples.ReportingServices.RSExplorer.ParameterValue[]):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.SetSchedulePropertiesAsync(System.String,System.String,Microsoft.Samples.ReportingServices.RSExplorer.ScheduleDefinition,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.SetSchedulePropertiesAsync(System.String,System.String,Microsoft.Samples.ReportingServices.RSExplorer.ScheduleDefinition):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.SetModelItemPoliciesAsync(System.String,System.String,Microsoft.Samples.ReportingServices.RSExplorer.Policy[],System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.SetModelItemPoliciesAsync(System.String,System.String,Microsoft.Samples.ReportingServices.RSExplorer.Policy[]):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.SetModelDrillthroughReportsAsync(System.String,System.String,Microsoft.Samples.ReportingServices.RSExplorer.ModelDrillthroughReport[],System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.SetModelDrillthroughReportsAsync(System.String,System.String,Microsoft.Samples.ReportingServices.RSExplorer.ModelDrillthroughReport[]):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.SetDataDrivenSubscriptionPropertiesAsync(System.String,Microsoft.Samples.ReportingServices.RSExplorer.ExtensionSettings,Microsoft.Samples.ReportingServices.RSExplorer.DataRetrievalPlan,System.String,System.String,System.String,Microsoft.Samples.ReportingServices.RSExplorer.ParameterValueOrFieldReference[],System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.SetDataDrivenSubscriptionPropertiesAsync(System.String,Microsoft.Samples.ReportingServices.RSExplorer.ExtensionSettings,Microsoft.Samples.ReportingServices.RSExplorer.DataRetrievalPlan,System.String,System.String,System.String,Microsoft.Samples.ReportingServices.RSExplorer.ParameterValueOrFieldReference[]):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.ResumeScheduleAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.PauseScheduleAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.ListScheduledReportsAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.ListModelItemChildrenAsync(System.String,System.String,System.Boolean,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.ListModelItemChildrenAsync(System.String,System.String,System.Boolean):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.ListModelDrillthroughReportsAsync(System.String,System.String,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.ListModelDrillthroughReportsAsync(System.String,System.String):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.InheritModelItemParentSecurityAsync(System.String,System.String,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.InheritModelItemParentSecurityAsync(System.String,System.String):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.GetSubscriptionPropertiesAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.GetSchedulePropertiesAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.GetReportParametersAsync(System.String,System.String,System.Boolean,Microsoft.Samples.ReportingServices.RSExplorer.ParameterValue[],Microsoft.Samples.ReportingServices.RSExplorer.DataSourceCredentials[],System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.GetReportParametersAsync(System.String,System.String,System.Boolean,Microsoft.Samples.ReportingServices.RSExplorer.ParameterValue[],Microsoft.Samples.ReportingServices.RSExplorer.DataSourceCredentials[]):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.GetModelItemPoliciesAsync(System.String,System.String,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.GetModelItemPoliciesAsync(System.String,System.String):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.GetModelItemPermissionsAsync(System.String,System.String,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.GetModelItemPermissionsAsync(System.String,System.String):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.GetDataDrivenSubscriptionPropertiesAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.FireEventAsync(System.String,System.String,System.Object):System.Void")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.FireEventAsync(System.String,System.String):System.Void")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.DeleteSubscriptionAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.DeleteScheduleAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.DeleteReportHistorySnapshotAsync(System.String,System.String,System.Object):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.DeleteReportHistorySnapshotAsync(System.String,System.String):System.Void", MessageId:="1#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005.CancelJobAsync(System.String,System.Object):System.Void", MessageId:="0#")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.ReportingService2005..ctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope:="member", Target:="Microsoft.Samples.ReportingServices.RSExplorer.Explorer..ctor()")> 
