//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40427.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.ReportingServices.AsynchronousRender.Properties {
    using System;
    using System.IO;
    using System.Resources;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the Strongly Typed Resource Builder
    // class via a tool like ResGen or Visual Studio.NET.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    class Resources {
        
        private static System.Resources.ResourceManager _resMgr;
        
        private static System.Globalization.CultureInfo _resCulture;
        
        /*FamANDAssem*/ internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if ((_resMgr == null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.Samples.ReportingServices.AsynchronousRender.Properties.Resources", typeof(Resources).Assembly);
                    _resMgr = temp;
                }
                return _resMgr;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return _resCulture;
            }
            set {
                _resCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Callback! Would you like to save the report to disk?".
        /// </summary>
        public static string callbackQuestionMessage {
            get {
                return ResourceManager.GetString("callbackQuestionMessage", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Report Rendered".
        /// </summary>
        public static string callbackQuestionMessageBoxTitle {
            get {
                return ResourceManager.GetString("callbackQuestionMessageBoxTitle", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "An error occurred:".
        /// </summary>
        public static string genericErrorMessage {
            get {
                return ResourceManager.GetString("genericErrorMessage", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Error".
        /// </summary>
        public static string genericErrorMessageBoxTitle {
            get {
                return ResourceManager.GetString("genericErrorMessageBoxTitle", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Rendering Report".
        /// </summary>
        public static string renderingReportText {
            get {
                return ResourceManager.GetString("renderingReportText", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "The report was saved successfully.".
        /// </summary>
        public static string reportSavedMessage {
            get {
                return ResourceManager.GetString("reportSavedMessage", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Ready.".
        /// </summary>
        public static string statusReadyText {
            get {
                return ResourceManager.GetString("statusReadyText", _resCulture);
            }
        }
    }
}
