'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class CustomSecurity
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.Samples.ReportingServices.CustomSecurity.CustomSecurity", GetType(CustomSecurity).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while attempting to add the account. .
        '''</summary>
        Friend Shared ReadOnly Property AddAccountError() As String
            Get
                Return ResourceManager.GetString("AddAccountError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Root element is not \&quot;AdminConfiguration\&quot; in config data..
        '''</summary>
        Friend Shared ReadOnly Property AdminConfiguration() As String
            Get
                Return ResourceManager.GetString("AdminConfiguration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logon.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogonResource1() As String
            Get
                Return ResourceManager.GetString("BtnLogonResource1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Register User.
        '''</summary>
        Friend Shared ReadOnly Property BtnRegisterResource1() As String
            Get
                Return ResourceManager.GetString("BtnRegisterResource1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid username or password.
        '''</summary>
        Friend Shared ReadOnly Property InvalidUsernamePassword() As String
            Get
                Return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQL Server  Reporting Services Sample.
        '''</summary>
        Friend Shared ReadOnly Property Label1Resource1() As String
            Get
                Return ResourceManager.GetString("Label1Resource1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property LblPwdResource1() As String
            Get
                Return ResourceManager.GetString("LblPwdResource1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Name:.
        '''</summary>
        Friend Shared ReadOnly Property LblUserResource1() As String
            Get
                Return ResourceManager.GetString("LblUserResource1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logon successful: User is authenticated..
        '''</summary>
        Friend Shared ReadOnly Property LoginSuccess() As String
            Get
                Return ResourceManager.GetString("LoginSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Url reservation found for the \&quot;ReportServerWebService\&quot; application..
        '''</summary>
        Friend Shared ReadOnly Property MissingUrlReservation() As String
            Get
                Return ResourceManager.GetString("MissingUrlReservation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of operation names don&apos;t match..
        '''</summary>
        Friend Shared ReadOnly Property OperationNameError() As String
            Get
                Return ResourceManager.GetString("OperationNameError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while attempting to get the ReportServer Url. .
        '''</summary>
        Friend Shared ReadOnly Property RSUrlError() As String
            Get
                Return ResourceManager.GetString("RSUrlError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unrecognized configuration element..
        '''</summary>
        Friend Shared ReadOnly Property UnrecognizedElement() As String
            Get
                Return ResourceManager.GetString("UnrecognizedElement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The user name that was entered contains characters not supported by report server custom authentication..
        '''</summary>
        Friend Shared ReadOnly Property UserNameError() As String
            Get
                Return ResourceManager.GetString("UserNameError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  user registered.
        '''</summary>
        Friend Shared ReadOnly Property UserRegistered() As String
            Get
                Return ResourceManager.GetString("UserRegistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception verifying user. .
        '''</summary>
        Friend Shared ReadOnly Property VerifyError() As String
            Get
                Return ResourceManager.GetString("VerifyError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while attempting to verify the user..
        '''</summary>
        Friend Shared ReadOnly Property VerifyUserException() As String
            Get
                Return ResourceManager.GetString("VerifyUserException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No WMI class found..
        '''</summary>
        Friend Shared ReadOnly Property WMIClassError() As String
            Get
                Return ResourceManager.GetString("WMIClassError", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
