'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version:2.0.40607.11
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.IO
Imports System.Resources

'Namespace My.Resources

'This class was auto-generated by the Strongly Typed Resource Builder
'class via a tool like ResGen or Visual Studio.NET.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''   A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Microsoft.VisualBasic.HideModuleName()> _
Module MyResources

    Private _resMgr As System.Resources.ResourceManager

    Private _resCulture As System.Globalization.CultureInfo

    '''<summary>
    '''   Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Public ReadOnly Property ResourceManager() As System.Resources.ResourceManager
        Get
            If (_resMgr Is Nothing) Then
                Dim temp As System.Resources.ResourceManager = New System.Resources.ResourceManager("Microsoft.Samples.ReportingServices.AsynchronousRender.MyResources", GetType(MyResources).Assembly)
                _resMgr = temp
            End If
            Return _resMgr
        End Get
    End Property

    '''<summary>
    '''   Overrides the current thread's CurrentUICulture property for all
    '''   resource lookups using this strongly typed resource class.
    '''</summary>
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Public Property Culture() As System.Globalization.CultureInfo
        Get
            Return _resCulture
        End Get
        Set(ByVal value As System.Globalization.CultureInfo)
            _resCulture = Value
        End Set
    End Property

    '''<summary>
    '''   Looks up a localized string similar to "Callback! Would you like to save the report to disk?".
    '''</summary>
    Public ReadOnly Property callbackQuestionMessage() As String
        Get
            Return ResourceManager.GetString("callbackQuestionMessage", _resCulture)
        End Get
    End Property

    '''<summary>
    '''   Looks up a localized string similar to "Report Rendered".
    '''</summary>
    Public ReadOnly Property callbackQuestionMessageBoxTitle() As String
        Get
            Return ResourceManager.GetString("callbackQuestionMessageBoxTitle", _resCulture)
        End Get
    End Property

    '''<summary>
    '''   Looks up a localized string similar to "An error occurred:".
    '''</summary>
    Public ReadOnly Property genericErrorMessage() As String
        Get
            Return ResourceManager.GetString("genericErrorMessage", _resCulture)
        End Get
    End Property

    '''<summary>
    '''   Looks up a localized string similar to "Error".
    '''</summary>
    Public ReadOnly Property genericErrorMessageBoxTitle() As String
        Get
            Return ResourceManager.GetString("genericErrorMessageBoxTitle", _resCulture)
        End Get
    End Property

    '''<summary>
    '''   Looks up a localized string similar to "Rendering Report".
    '''</summary>
    Public ReadOnly Property renderingReportText() As String
        Get
            Return ResourceManager.GetString("renderingReportText", _resCulture)
        End Get
    End Property

    '''<summary>
    '''   Looks up a localized string similar to "The report was saved successfully.".
    '''</summary>
    Public ReadOnly Property reportSavedMessage() As String
        Get
            Return ResourceManager.GetString("reportSavedMessage", _resCulture)
        End Get
    End Property

    '''<summary>
    '''   Looks up a localized string similar to "Ready.".
    '''</summary>
    Public ReadOnly Property statusReadyText() As String
        Get
            Return ResourceManager.GetString("statusReadyText", _resCulture)
        End Get
    End Property
End Module
'End Namespace
